from snakemake.utils import min_version

min_version("6.0")

from shutil import copyfile, move, rmtree
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

from os.path import normpath
from itertools import chain
import pandas as pd

FIGURES_MAPS = [
    "capacity_map_base_pie.png",
    "capacity_map_base_transmission.png",
    "capacity_map_optimized_pie.png",
    "capacity_map_optimized_transmission.png",
    "capacity_map_new_pie.png",
    "capacity_map_new_transmission.png",
    # "lmp_map.pdf",
]

STATISTICS_TABLES = [
    "statistics.csv",
    "statistics_dissaggregated.csv",
    "cost_breakdown.csv",
    "generators.csv",
    "storage_units.csv",
    "links.csv",
    "buses.csv",
    "lines.csv",
    "stores.csv",
    "global_constraints.csv",
]

# --------------------------- Workflow constraints --------------------------- #
localrules:
    dag,
    clean,


wildcard_constraints:
    case="[A-Za-z0-9._-]+",
    ll="(v|c)([0-9\.]+|opt|inf|all)|all",
    opts="[-+a-zA-Z0-9\.]*",


# -------------------------- Config and Subworkflows ------------------------- #


# Merge subworkflow configs and main config
configfile: "config/config.default.yaml"
configfile: "config/config.cluster.yaml"
configfile: "config/config.common.yaml"
configfile: "config/config.plotting.yaml"
configfile: "config/config.api.yaml"
configfile: "config/cases.yaml"


run = config.get("run", {})
CASES_ENABLED = bool(config.get("cases"))
CASES = list(config.get("cases", {})) if CASES_ENABLED else [run.get("name") or "default"]
RDIR = run["name"] + "/" if run.get("name") and not CASES_ENABLED else ""
CDIR = "" if CASES_ENABLED or run.get("shared_cutouts") else RDIR

LOGS = "logs/" + RDIR
BENCHMARKS = "benchmarks/" + RDIR
DATA = "data/"
RESOURCES = "resources/shared/"
CASE_RESOURCES = "resources/cases/{case}/" if CASES_ENABLED else "resources/cases/" + RDIR
CASE_RESOURCES_WC = CASE_RESOURCES.replace("{case}", "{{case}}")
RESULTS = "results/" + RDIR
CASE_RESULTS = "results/{case}/" if CASES_ENABLED else RESULTS
CASE_RESULTS_WC = CASE_RESULTS.replace("{case}", "{{case}}")
CASE_LOGS = "logs/{case}/" if CASES_ENABLED else LOGS
CASE_BENCHMARKS = "benchmarks/{case}/" if CASES_ENABLED else BENCHMARKS
FIGURE_ROOT = CASE_RESULTS + "figure/"
def result_network_path(suffix=""):
    return CASE_RESULTS + "network/network" + suffix + ".nc"


def result_config_path():
    return CASE_RESULTS + "config/config.yaml"


def result_figure_path(*parts, figure="{figure}"):
    return FIGURE_ROOT + "/".join(parts) + "/" + figure


include: "rules/common.smk"
include: "rules/retrieve.smk"
include: "rules/build_electricity.smk"
include: "rules/solve_electricity.smk"
include: "rules/postprocess.smk"


normalize_electricity_config(config)

# ----------------------------------- Rules ---------------------------------- #


def iter_case_configs():
    if CASES_ENABLED:
        for case_name in CASES:
            yield case_name, case_config(case_name)
    else:
        yield CASES[0], config


def expand_case_targets(pattern, **kwargs):
    targets = []
    for case_name, cfg in iter_case_configs():
        targets.extend(expand_case_targets_for(case_name, cfg, pattern, **kwargs))
    return targets


def expand_case_targets_for(case_name, cfg, pattern, **kwargs):
    expand_kwargs = dict(cfg["scenario"])
    if CASES_ENABLED:
        expand_kwargs["case"] = [case_name]
    expand_kwargs.update(kwargs)
    return expand(pattern, **expand_kwargs)


def electricity_figures(wildcards):
    figs = []
    for case_name, cfg in iter_case_configs():
        figs.append(
            expand_case_targets_for(
                case_name,
                cfg,
                result_figure_path("maps"),
                figure=FIGURES_MAPS,
            )
        )
        figs.append(
            expand_case_targets_for(
                case_name,
                cfg,
                result_figure_path("statistics"),
                figure=STATISTICS_TABLES,
            )
        )
    return list(chain(*figs))


rule all:
    input:
        #"repo_data/dag.jpg",
        electricity_figures,


rule data_model:
    input:
        expand_case_targets(
            CASE_RESOURCES
            + "elec_ec_l{ll}_{opts}.nc",
        ),


# Create DAG with-
# snakemake --rulegraph all | sed -n "/digraph/,\$p" | dot -Tpng -o repo_data/dag.jpg
# snakemake --dag -F | sed -n "/digraph/,\$p" | dot -Tpng -o repo_data/dag.jpg
rule dag:
    message:
        "Creating DAG of workflow."
    output:
        dot="repo_data/dag.dot",
        jpg="repo_data/dag.jpg",
    shell:
        """
        snakemake --rulegraph all | sed -n "/digraph/,\$p" > {output.dot}
        dot -Tjpg -o {output.jpg} {output.dot}
        """


rule clean:
    message:
        "Remove all build results but keep downloaded data."
    run:
        import shutil

        shutil.rmtree("resources", ignore_errors=True)
        shutil.rmtree("results", ignore_errors=True)
        print("Data downloaded to data/ has not been cleaned.")
